# <font color="purple"><h3 align="center">DataFrame Basics Tutorial</h3></font>

## **Dataframe is most commonly used object in pandas. It is a table like datastructure containing rows and columns similar to excel spreadsheet**

In [0]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}
df = pd.DataFrame(weather_data)
df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/pandas/2_dataframe_basics/weather_data.csv")
df

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [0]:
df.shape # rows, columns = df.shape

(6, 4)

## <font color='blue'>Rows</font>

In [0]:
df.head() # df.head(3)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [0]:
df.tail() # df.tail(2)

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [0]:
df[1:3]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

## <font color='blue'>Columns</font>

In [0]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [0]:
df['day'] # or df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [0]:
type(df['day'])

pandas.core.series.Series

In [0]:
df[['day','temperature']]

        day  temperature
0  1/1/2017           32
1  1/2/2017           35
2  1/3/2017           28
3  1/4/2017           24
4  1/5/2017           32
5  1/6/2017           31

## <font color='blue'>Operations On DataFrame</font>

In [0]:
df['temperature'].max()  # min, std, mean, describe

35

In [0]:
df[df['temperature']>32]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [0]:
df['day'][df['temperature'] == df['temperature'].max()] # Kinda doing SQL in pandas

1    1/2/2017
Name: day, dtype: object

In [0]:
df['temperature'] == df['temperature'].max()

0    False
1     True
2    False
3    False
4    False
5    False
Name: temperature, dtype: bool

In [0]:
df[df['temperature'] == df['temperature'].max()] # Kinda doing SQL in pandas

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [0]:
df['temperature'].std()

3.8297084310253524

In [0]:
df['event'].max() # But mean() won't work since data type is string

'Sunny'

In [0]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

**Google pandas series operations to find out list of all operations**
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.html

## <font color='blue'>set_index</font>

In [0]:
df.set_index('day')   # pd.read_csv("weather.csv",parse_date=['day'])
df

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [0]:
df.set_index('day', inplace=True) # modify original dataframe

In [0]:
df

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [0]:
df.index

Index(['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'], dtype='object', name='day')

In [0]:
df.loc['1/2/2017']

temperature       35
windspeed          7
event          Sunny
Name: 1/2/2017, dtype: object

In [0]:
df.reset_index(inplace=True)
df.head()

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [0]:
df.set_index('event',inplace=True) # this is kind of building a hash map using event as a key
df

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [0]:
df.loc['Snow']

            day  temperature  windspeed
event
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7