# Pandas Selection and Indexing

![alt text](https://shanelynnwebsite-mid9n9g1q9y8tt.netdna-ssl.com/wp-content/uploads/2016/10/Pandas-selections-and-indexing-768x549.png)

In [1]:
import pandas as pd
import random

In [2]:
# read the data from the downloaded CSV file.
data = pd.read_csv('https://s3-eu-west-1.amazonaws.com/shanebucket/downloads/uk-500.csv')

In [3]:
data.head(5)

  first_name  ...                                   web
0    Aleshia  ...  http://www.alandrosenburgcpapc.co.uk
1       Evan  ...     http://www.capgeminiamerica.co.uk
2     France  ...      http://www.elliottjohnwesq.co.uk
3    Ulysses  ...          http://www.mcmahanbenl.co.uk
4     Tyisha  ...        http://www.champagneroom.co.uk

[5 rows x 11 columns]

# 1. Selecting pandas data using “iloc”

In [4]:
# Single selections using iloc and DataFrame
# Rows:
data.iloc[0] # first row of data frame (Aleshia Tomkiewicz) - Note a Series data type output.

first_name                                   Aleshia
last_name                                 Tomkiewicz
company_name                 Alan D Rosenburg Cpa Pc
address                                 14 Taylor St
city                               St. Stephens Ward
county                                          Kent
postal                                       CT2 7PP
phone1                                  01835-703597
phone2                                  01944-369967
email                        atomkiewicz@hotmail.com
web             http://www.alandrosenburgcpapc.co.uk
Name: 0, dtype: object

In [5]:
data.iloc[1] # second row of data frame (Evan Zigomalas)

first_name                                   Evan
last_name                               Zigomalas
company_name                   Cap Gemini America
address                               5 Binney St
city                                   Abbey Ward
county                            Buckinghamshire
postal                                   HP11 2AX
phone1                               01937-864715
phone2                               01714-737668
email                    evan.zigomalas@gmail.com
web             http://www.capgeminiamerica.co.uk
Name: 1, dtype: object

In [6]:
data.iloc[-1] # last row of data frame (Mi Richan)

first_name                                               Mi
last_name                                            Richan
company_name                 Nelson Wright Haworth Golf Crs
address                                     6 Norwood Grove
city                                      Tanworth-in-Arden
county                                         Warwickshire
postal                                              B94 5RZ
phone1                                         01451-785624
phone2                                         01202-738406
email                                        mi@hotmail.com
web             http://www.nelsonwrighthaworthgolfcrs.co.uk
Name: 499, dtype: object

In [7]:
# Columns:
data.iloc[:,0] # first column of data frame (first_name)

0        Aleshia
1           Evan
2         France
3        Ulysses
4         Tyisha
         ...
495        Avery
496         Reid
497    Charlette
498    Celestina
499           Mi
Name: first_name, Length: 500, dtype: object

In [8]:
data.iloc[:,1] # second column of data frame (last_name)

0      Tomkiewicz
1       Zigomalas
2         Andrade
3       Mcwalters
4          Veness
          ...
495          Veit
496       Euresti
497      Brenning
498         Keeny
499        Richan
Name: last_name, Length: 500, dtype: object

In [9]:
data.iloc[:,-1] # last column of data frame (id)

0             http://www.alandrosenburgcpapc.co.uk
1                http://www.capgeminiamerica.co.uk
2                 http://www.elliottjohnwesq.co.uk
3                     http://www.mcmahanbenl.co.uk
4                   http://www.champagneroom.co.uk
                          ...
495      http://www.plazagourmetdelicatessen.co.uk
496             http://www.fitzgeraldedwardj.co.uk
497               http://www.fureyassociates.co.uk
498         http://www.bfgfederalcreditunion.co.uk
499    http://www.nelsonwrighthaworthgolfcrs.co.uk
Name: web, Length: 500, dtype: object

In [10]:
# Multiple row and column selections using iloc and DataFrame
data.iloc[0:5] # first five rows of dataframe

  first_name  ...                                   web
0    Aleshia  ...  http://www.alandrosenburgcpapc.co.uk
1       Evan  ...     http://www.capgeminiamerica.co.uk
2     France  ...      http://www.elliottjohnwesq.co.uk
3    Ulysses  ...          http://www.mcmahanbenl.co.uk
4     Tyisha  ...        http://www.champagneroom.co.uk

[5 rows x 11 columns]

In [11]:
data.iloc[:, 0:2] # first two columns of data frame with all rows

    first_name   last_name
0      Aleshia  Tomkiewicz
1         Evan   Zigomalas
2       France     Andrade
3      Ulysses   Mcwalters
4       Tyisha      Veness
..         ...         ...
495      Avery        Veit
496       Reid     Euresti
497  Charlette    Brenning
498  Celestina       Keeny
499         Mi      Richan

[500 rows x 2 columns]

In [12]:
data.iloc[[0,3,6,24], [0,5,6]] # 1st, 4th, 7th, 25th row + 1st 6th 7th columns.

   first_name        county    postal
0     Aleshia          Kent   CT2 7PP
3     Ulysses  Lincolnshire  DN36 5RP
6        Marg   Southampton  SO14 3TY
24       Tess   West Sussex  PO19 1RH

In [13]:
data.iloc[0:5, 5:8] # first 5 rows and 5th, 6th, 7th columns of data frame (county -> phone1).

            county    postal        phone1
0             Kent   CT2 7PP  01835-703597
1  Buckinghamshire  HP11 2AX  01937-864715
2      Bournemouth   BH6 3BE  01347-368222
3     Lincolnshire  DN36 5RP  01912-771311
4    West Midlands   B70 9DT  01547-429341

# 2. Selecting pandas data using “loc”

The Pandas loc indexer can be used with DataFrames for two different use cases:

a.) Selecting rows by label/index

b.) Selecting rows with a boolean / conditional lookup

The loc indexer is used with the same syntax as iloc: data.loc[<row selection>, <column selection>] .

## 2a. Label-based / Index-based indexing using .loc

In [14]:
data.set_index("last_name", inplace=True)
data.head()

           first_name  ...                                   web
last_name              ...
Tomkiewicz    Aleshia  ...  http://www.alandrosenburgcpapc.co.uk
Zigomalas        Evan  ...     http://www.capgeminiamerica.co.uk
Andrade        France  ...      http://www.elliottjohnwesq.co.uk
Mcwalters     Ulysses  ...          http://www.mcmahanbenl.co.uk
Veness         Tyisha  ...        http://www.champagneroom.co.uk

[5 rows x 10 columns]

In [15]:
# Select rows with index values 'Andrade' and 'Veness', with all columns between 'city' and 'email'
data.loc[['Andrade', 'Veness'], 'city':'email']

                                     city  ...                       email
last_name                                  ...
Andrade    East Southbourne and Tuckton W  ...  france.andrade@hotmail.com
Veness         Greets Green and Lyng Ward  ...   tyisha.veness@hotmail.com

[2 rows x 6 columns]

In [16]:
# Select same rows, with just 'first_name', 'address' and 'city' columns
data.loc['Andrade':'Veness', ['first_name', 'address', 'city']]

          first_name            address                            city
last_name
Andrade       France       8 Moor Place  East Southbourne and Tuckton W
Mcwalters    Ulysses      505 Exeter Rd              Hawerby cum Beesby
Veness        Tyisha  5396 Forth Street      Greets Green and Lyng Ward

## 2b. Boolean / Logical indexing using .loc

In [17]:
# Select rows with first name Antonio, # and all columns between 'city' and 'email'
data.loc[data['first_name'] == 'Antonio', 'city':'email']

                                      city  ...                            email
last_name                                   ...
Villamarin  Little Parndon and Hare Street  ...     antonio.villamarin@gmail.com
Glasford                    Gaer Community  ...  antonio_glasford@glasford.co.uk
Heilig                            Ipplepen  ...         antonio.heilig@gmail.com

[3 rows x 6 columns]

In [18]:
# Select rows where the email column ends with 'hotmail.com', include all columns
data.loc[data['email'].str.endswith("hotmail.com")]

           first_name  ...                                          web
last_name              ...
Tomkiewicz    Aleshia  ...         http://www.alandrosenburgcpapc.co.uk
Andrade        France  ...             http://www.elliottjohnwesq.co.uk
Mcwalters     Ulysses  ...                 http://www.mcmahanbenl.co.uk
Veness         Tyisha  ...               http://www.champagneroom.co.uk
Grasmick         Marg  ...     http://www.wranglehillautoauctslvg.co.uk
...               ...  ...                                          ...
Gaucher        Sophia  ...               http://www.tcesystemsinc.co.uk
Ausdemore      Rosita  ...              http://www.jurdemscottesq.co.uk
Stancil          Huey  ...                http://www.lindnerfunds.co.uk
Fiorino        Elbert  ...            http://www.donaldgnelsonesq.co.uk
Richan             Mi  ...  http://www.nelsonwrighthaworthgolfcrs.co.uk

[114 rows x 10 columns]

In [19]:
# Select rows with last_name equal to some values, all columns
data.loc[data['first_name'].isin(['France', 'Tyisha', 'Eric'])]

          first_name  ...                                   web
last_name             ...
Andrade       France  ...      http://www.elliottjohnwesq.co.uk
Veness        Tyisha  ...        http://www.champagneroom.co.uk
Rampy           Eric  ...  http://www.thompsonmichaelcesq.co.uk

[3 rows x 10 columns]

In [20]:
# Select rows with first name Antonio AND hotmail email addresses
data.loc[data['email'].str.endswith("gmail.com") & (data['first_name'] == 'Antonio')]

           first_name  ...                                  web
last_name              ...
Villamarin    Antonio  ...     http://www.combssheetmetal.co.uk
Heilig        Antonio  ...  http://www.radissonsuitehotel.co.uk

[2 rows x 10 columns]

In [21]:
# # A lambda function that yields True/False values can also be used.
# Select rows where the company name has 4 words in it.
data.loc[data['company_name'].apply(lambda x: len(x.split(' ')) == 4)]

            first_name  ...                                         web
last_name               ...
Andrade         France  ...            http://www.elliottjohnwesq.co.uk
Rampy             Eric  ...        http://www.thompsonmichaelcesq.co.uk
Erm        Charlesetta  ...               http://www.cainjohnmesq.co.uk
Throssell      Michell  ...            http://www.weissspirtguyer.co.uk
Kanne            Edgar  ...          http://www.crowankennethwesq.co.uk
...                ...  ...                                         ...
Alsaqri          Ahmad  ...  http://www.allianceconstructioncoinc.co.uk
Reibman     Jacquelyne  ...          http://www.greatclipsforhair.co.uk
Kono          Isabelle  ...  http://www.rockspringspetroleumequip.co.uk
Fiorino         Elbert  ...           http://www.donaldgnelsonesq.co.uk
Keeny        Celestina  ...      http://www.bfgfederalcreditunion.co.uk

[192 rows x 10 columns]

In [22]:
data.head()

           first_name  ...                                   web
last_name              ...
Tomkiewicz    Aleshia  ...  http://www.alandrosenburgcpapc.co.uk
Zigomalas        Evan  ...     http://www.capgeminiamerica.co.uk
Andrade        France  ...      http://www.elliottjohnwesq.co.uk
Mcwalters     Ulysses  ...          http://www.mcmahanbenl.co.uk
Veness         Tyisha  ...        http://www.champagneroom.co.uk

[5 rows x 10 columns]

In [23]:
data.reset_index(inplace=True)

In [24]:
data.head()

    last_name  ...                                   web
0  Tomkiewicz  ...  http://www.alandrosenburgcpapc.co.uk
1   Zigomalas  ...     http://www.capgeminiamerica.co.uk
2     Andrade  ...      http://www.elliottjohnwesq.co.uk
3   Mcwalters  ...          http://www.mcmahanbenl.co.uk
4      Veness  ...        http://www.champagneroom.co.uk

[5 rows x 11 columns]

In [27]:
data[(data['county']=='Kent') & (data['first_name']=='Aleshia')]

    last_name  ...                                   web
0  Tomkiewicz  ...  http://www.alandrosenburgcpapc.co.uk

[1 rows x 11 columns]

In [ ]:
# similarly or, and other logical operators

# QUIZ

[link text](https://forms.office.com/Pages/ResponsePage.aspx?id=o835AF4H5USqC6ujrdZTn63NXi4eP7xHpYuejR_M4qdUNk9QUFlQOThQUUdKM080RFhTR1YzTlYwUC4u)

https://forms.office.com/Pages/ResponsePage.aspx?id=o835AF4H5USqC6ujrdZTn63NXi4eP7xHpYuejR_M4qdUNk9QUFlQOThQUUdKM080RFhTR1YzTlYwUC4u