In [ ]:
import pandas as pd

# Basic Pandas

In [ ]:
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv',sep=';')

1. What is the number of rows and columns of this dataset

In [ ]:
df.shape

(1599, 12)

2. what is the datatype of column pH

In [ ]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [ ]:
3. What is the standard deviation of the density column

In [ ]:
df.describe()

       fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

4. How many unique pH values are there in the dataset

In [ ]:
df['pH'].value_counts()

3.30    57
3.36    56
3.26    53
3.38    48
3.39    48
        ..
2.95     1
3.74     1
2.87     1
2.90     1
3.70     1
Name: pH, Length: 89, dtype: int64

# Selection

In [ ]:
df.iloc[:,[3,4,6]].head()

   residual sugar  chlorides  total sulfur dioxide
0             1.9      0.076                  34.0
1             2.6      0.098                  67.0
2             2.3      0.092                  54.0
3             1.9      0.075                  60.0
4             1.9      0.076                  34.0

In [ ]:
df.iloc[:,[3,4,6]]

      residual sugar  chlorides  total sulfur dioxide
0                1.9      0.076                  34.0
1                2.6      0.098                  67.0
2                2.3      0.092                  54.0
3                1.9      0.075                  60.0
4                1.9      0.076                  34.0
...              ...        ...                   ...
1594             2.0      0.090                  44.0
1595             2.2      0.062                  51.0
1596             2.3      0.076                  40.0
1597             2.0      0.075                  44.0
1598             3.6      0.067                  42.0

[1599 rows x 3 columns]

In [ ]:
df.loc[:,[3,4,6]]

KeyError: ignored

In [ ]:
df.iloc[[4,8],[7,9]]

   density  sulphates
4   0.9978       0.56
8   0.9968       0.57

In [ ]:
df.head(10)

   fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5
5            7.4              0.66         0.00  ...       0.56      9.4        5
6            7.9              0.60         0.06  ...       0.46      9.4        5
7            7.3              0.65         0.00  ...       0.47     10.0        7
8            7.8              0.58         0.02  ...       0.57      9.5        7
9            7.5              0.50         0.36  ...       0.80     10.5        5

[10 rows x 12 columns]

In [ ]:
df.iloc[[4,8],['density','sulphates']]

IndexError: ignored

In [ ]:
df.set_index('density',inplace=True)

In [ ]:
df.loc[0.9968].count()

fixed acidity           35
volatile acidity        35
citric acid             35
residual sugar          35
chlorides               35
free sulfur dioxide     35
total sulfur dioxide    35
pH                      35
sulphates               35
alcohol                 35
quality                 35
dtype: int64

In [ ]:
df.reset_index(inplace=True)

In [ ]:
df

      density  fixed acidity  volatile acidity  ...  sulphates  alcohol  quality
0     0.99780            7.4             0.700  ...       0.56      9.4        5
1     0.99680            7.8             0.880  ...       0.68      9.8        5
2     0.99700            7.8             0.760  ...       0.65      9.8        5
3     0.99800           11.2             0.280  ...       0.58      9.8        6
4     0.99780            7.4             0.700  ...       0.56      9.4        5
...       ...            ...               ...  ...        ...      ...      ...
1594  0.99490            6.2             0.600  ...       0.58     10.5        5
1595  0.99512            5.9             0.550  ...       0.76     11.2        6
1596  0.99574            6.3             0.510  ...       0.75     11.0        6
1597  0.99547            5.9             0.645  ...       0.71     10.2        5
1598  0.99549            6.0             0.310  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [ ]:
df[(df['quality']==5 ) & (df['alcohol']==9.8)].shape

(49, 12)

In [ ]:
df[(df['fixed acidity']>5 ) |  (df['residual sugar']<2)].density.sum()

1588.8379

# Groupby

In [1]:
import pandas as pd
df=pd.read_csv('https://theunitedstates.io/congress-legislators/legislators-historical.csv')

In [2]:
df.head()

  last_name  first_name  ... icpsr_id                    wikipedia_id
0   Bassett     Richard  ...    507.0    Richard Bassett (politician)
1     Bland  Theodorick  ...    786.0  Theodorick Bland (congressman)
2     Burke     Aedanus  ...   1260.0                   Aedanus Burke
3   Carroll      Daniel  ...   1538.0                  Daniel Carroll
4    Clymer      George  ...   1859.0                   George Clymer

[5 rows x 34 columns]

In [5]:
df.isnull().sum()

last_name                 0
first_name                0
middle_name            3619
suffix                11559
nickname              11753
full_name             11632
birthday                551
gender                    0
type                      0
state                     0
district               1830
senate_class          10151
party                   232
url                   11327
address               11624
phone                 11628
contact_form          11759
rss_url               11772
twitter               11981
facebook              11981
youtube               11981
youtube_id            11981
bioguide_id               0
thomas_id             10175
opensecrets_id        11308
lis_id                11789
fec_ids               11435
cspan_id              11559
govtrack_id               0
votesmart_id          11415
ballotpedia_id        11785
washington_post_id    11981
icpsr_id                211
wikipedia_id              2
dtype: int64

In [3]:
n_by_state = df.groupby("state")["last_name"].count()

In [4]:
n_by_state

state
AK      16
AL     206
AR     117
AS       2
AZ      48
CA     363
CO      90
CT     240
DC       2
DE      97
DK       9
FL     155
GA     310
GU       4
HI      23
IA     202
ID      59
IL     486
IN     341
KS     141
KY     373
LA     197
MA     426
MD     305
ME     175
MI     294
MN     160
MO     333
MS     155
MT      52
NC     354
ND      44
NE     127
NH     181
NJ     359
NM      54
NV      56
NY    1462
OH     674
OK      92
OL       2
OR      89
PA    1053
PI      13
PR      19
RI     107
SC     251
SD      51
TN     299
TX     257
UT      53
VA     432
VI       4
VT     115
WA      95
WI     197
WV     120
WY      40
Name: last_name, dtype: int64

In [6]:
df.groupby(["state", "gender"])["last_name"].count()

state  gender
AK     M          16
AL     F           3
       M         203
AR     F           5
       M         112
                ...
WI     M         197
WV     F           1
       M         119
WY     F           2
       M          38
Name: last_name, Length: 104, dtype: int64

In [8]:
n_by_state = df.groupby("state")["last_name"].count().sort_values()

In [10]:
n_by_state.tail()

state
VA     432
IL     486
OH     674
PA    1053
NY    1462
Name: last_name, dtype: int64

In [16]:
df.groupby(['last_name']).sum().head(20)

              district  senate_class  ...  washington_post_id  icpsr_id
last_name                             ...
Aandahl            0.0           0.0  ...                 0.0       1.0
Abbitt             4.0           0.0  ...                 0.0       2.0
Abbott            15.0           2.0  ...                 0.0      33.0
Abdnor             0.0           3.0  ...                 0.0   14000.0
Abel               0.0           2.0  ...                 0.0       9.0
Abele             10.0           0.0  ...                 0.0   10568.0
Abercrombie        2.0           0.0  ...                 0.0   15266.0
Abernethy          4.0           0.0  ...                 0.0      25.0
Abourezk           0.0           2.0  ...                 0.0   13000.0
Abraham            0.0           1.0  ...                 0.0   49500.0
Abzug             20.0           0.0  ...                 0.0   13001.0
Acevedo-Vilá       0.0           0.0  ...                 0.0       0.0
Acheson           24.0           0.0  ...                 0.0      14.0
Acker              6.0           0.0  ...                 0.0      15.0
Ackerman          10.0           0.0  ...                 0.0   15016.0
Acklen             3.0           0.0  ...                 0.0      17.0
Adair             34.0           0.0  ...                 0.0      78.0
Adams            142.0           9.0  ...                 0.0   32401.0
Adamson            4.0           0.0  ...                 0.0      44.0
Addabbo            6.0           0.0  ...                 0.0   10500.0

[20 rows x 12 columns]

In [13]:
df.shape

(11981, 34)

In [15]:
df[df['last_name']=='Abbott']

     last_name first_name  ... icpsr_id                      wikipedia_id
1082    Abbott       Joel  ...      5.0           Joel Abbot (politician)
2469    Abbott       Amos  ...      3.0                       Amos Abbott
3171    Abbott   Nehemiah  ...      8.0                   Nehemiah Abbott
3906    Abbott     Joseph  ...      6.0              Joseph Carter Abbott
4397    Abbott     Josiah  ...      7.0             Josiah Gardner Abbott
5877    Abbott         Jo  ...      4.0  Joseph Abbott (Texas politician)

[6 rows x 34 columns]

In [17]:
grp=df.groupby(['last_name'])

In [19]:
import numpy as np

In [20]:
grp['icpsr_id'].agg([np.sum, np.mean, np.std])

                   sum          mean          std
last_name
Aandahl            1.0      1.000000          NaN
Abbitt             2.0      2.000000          NaN
Abbott            33.0      5.500000     1.870829
Abdnor         14000.0  14000.000000          NaN
Abel               9.0      9.000000          NaN
...                ...           ...          ...
Zwach          11060.0  11060.000000          NaN
de Lugo            0.0           NaN          NaN
de la Garza    10716.0  10716.000000          NaN
deGraffenried   2468.0   2468.000000          NaN
du Pont        18577.0   6192.333333  5907.736651

[5468 rows x 3 columns]